[general]
import = ["~/.config/alacritty/catppuccin.toml"]
live_config_reload = true

[window]
opacity = 1

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/usr/bin/zsh"

[window.padding]
x = 15
y = 15

#[colors.primary]
#background = "#11111b"

#[colors.vi_mode_cursor]
#cursor = "#a6e3a1"

[cursor]
thickness = 0.2

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 13

[font.normal]
family = "RobotoMono Nerd Font Propo"
style = "Regular"

[font.bold]
family = "RobotoMono Nerd Font Propo"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font Propo"
style = "Italic"

[mouse]
hide_when_typing = true

